####################################################################
# !!! REMINDER !!!                                                 #
# Don't forget to run `manala up` each time you update this file ! #
####################################################################

manala:
    recipe: lazy.ansible

###########
# Project #
###########

project:
    name: manala-ansible-path

##########
# System #
##########

system:
    git:
        config: |
            # Silence false positive dubious ownership errors
            [safe]
            directory = *
    ansible:
        version: 2.16.9
        config: |
            [defaults]
            force_color = True
            retry_files_enabled = False
    ansible-lint:
        version: 24.7.0
