name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up system
        uses: ./.manala/github/system/setup

      - name: Sanity
        run: |
          make test.sanity VERBOSE=1

      - name: Units
        run: |
          make test.units VERBOSE=1 COVERAGE=1

      - name: Integration
        run: |
          make test.integration VERBOSE=1 COVERAGE=1

      - name: Coverage
        run: |
          make test.coverage VERBOSE=1

      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
